## Working with JSON Data from GitHub

In [1]:
import pandas as pd # This library is to enable me to transform the JSON data into a dataframe
import requests # Importing the library needed to read the JSON Data link to be used

In [2]:
# Assigning my JSON data raw github link to an identifier(url) 
url = 'https://raw.githubusercontent.com/DerickMenje/LuxDevHq_Weekly_Assignments/refs/heads/main/Working%20with%20JSON%20Data%20From%20Github/MOCK_DATA.json'

In [3]:
# Sending the GET request
response = requests.get(url)

In [4]:
# Parsing the JSON content into a dataframe
data = response.json()

In [11]:
# Converting the JSON into a dataframe
df = pd.DataFrame(data)
df.head()

,id,first_name,last_name,email,gender,stock_name,stock_sector
0,1,Erich,Howick,ehowick0@purevolume.com,Male,Century Aluminum Company,Basic Industries
1,2,Johanna,Pettiford,jpettiford1@uol.com.br,Female,Great Ajax Corp.,Consumer Services
2,3,Bobbi,MacGillivrie,bmacgillivrie2@deliciousdays.com,Female,Jensyn Acquistion Corp.,Finance
3,4,Janice,Kohrt,jkohrt3@google.com.br,Female,Eastman Kodak Company,Miscellaneous
4,5,Tori,Sothern,tsothern4@ucoz.ru,Female,Dynegy Inc.,n/a

In [12]:
# Saving the data frame as a CSV
df.to_csv('MyMock_Up.csv', index = False)

# index = False ensures that the csv does not add another column of row number

## Working with Dummy JSON API Endpoints

In [16]:
url_1 = 'https://dummyjson.com/products'
url_2 = 'https://dummyjson.com/carts'

In [24]:
response_1 = requests.get(url_1)
response_2 = requests.get(url_2)

data_1 = response_1.json()
data_2 = response_2.json()


# Flattening the Products and carts lists into a table; This breaks down the items in the product into columns.
df_products = pd.json_normalize(data_1['products'])
df_carts = pd.json_normalize(data_2['carts'])

# Converting to CSV
df_products.to_csv('Products.csv', index = False)
df_carts.to_csv('carts.csv', index = False)

In [25]:
df_products.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png